### ISSUE TITLE
Help wanted

### ISSUE THREAD

**Issue by OlegVN** [hyphop/miZy-linux-kernel#1]
Добрый день!
Огромное спасибо за проделанную работу!
К сожалению модуль ax88179_178a.ko не установился на моей системе ((
root@OpenWrt:/1# insmod ax88179_178a.ko
failed to insert ax88179_178a.ko

dmesg даёт ошибки типа:
[ 6770.202282] ax88179_178a: disagrees about version of symbol usb_alloc_urb
[ 6770.202326] ax88179_178a: Unknown symbol usb_alloc_urb (err -22)
[ 6770.202411] ax88179_178a: disagrees about version of symbol usbnet_set_msglevel
[ 6770.202436] ax88179_178a: Unknown symbol usbnet_set_msglevel (err -22)
[ 6770.202467] ax88179_178a: disagrees about version of symbol mii_ethtool_sset
и т.д.

Есть ли какой-то способ принудительно поставить этот модуль в мою систему?
И Вы писали, что можно заменить ядро с модулями на ваше... Могли бы Вы написать как это сделать по шагам..?

**Comment by OlegVN** [comment]
модуль ax88179_178a.ko брал здесь:
https://github.com/hyphop/miZy-linux-kernel/releases/download/light/miZy.linux.kernel.light.modules.full.tar.gz

**Comment by hyphop** [comment]
совет 1
сначала
modprobe usbnet
а потом 
insmod ax88179_178a.ko
если не работает то нужно брать целиком ядро с модулями
1) копируй ядро и модули ну и в загузчике проверить чтоб загружалось имеено это ядро
тут все стандартно - читаем подробнее на openwrt сайте
или
2) бери mizy там уже нужное ядро копируй модуль и проверяй

**Comment by OlegVN** [comment]
Могли бы Вы кинуть ссылку на инструкцию по замене ядра..? Не понимаю что именно и чем надо заменить, как исправить загрузчик и т.д.
Прошу прощение за навязчивость, но я не смог найти информации по этой теме. 
Весьма благодарен за помощь

**Comment by OlegVN** [comment]
modprobe usbnet
insmod ax88179_178a.ko
не дал результата..

**Comment by hyphop** [comment]
ищите читайте - вся информация в сети есть - конечно не в одном месте по ссылке как вам хочется - работайте изучайте - без этого никак 
все разжевывать и учить не мой профиль - пардон)

**Comment by OlegVN** [comment]
Ok, спасибо и на этом, и так много времени занял :)
